In [18]:
#requires an API key and host to work properly
from draw_analysis.get_api import GetApiFootballData

In [2]:
credentials_sample = {
    'x-rapidapi-key': '',
    'x-rapidapi-host':''
    }

In [3]:
help(GetApiFootballData)

Help on class GetApiFootballData in module draw_analysis.get_api:

class GetApiFootballData(builtins.object)
 |  GetApiFootballData(credentials)
 |
 |  GetApiFootballData class is used to search and download fixtures data from API-Football-Beta.
 |
 |  The class allows to easily search for the looking league ID by calling function'get_country_leagues_overview'
 |  with country name.
 |
 |  To check details and league seasons availability in API-Football-Beta source call function 'get_seasons_details'.
 |
 |  Proper operation require API headers, which can be obtained by registering at https://rapidapi.com/.
 |
 |  For more information about API-Football-Beta visit https://rapidapi.com/api-sports/api/api-football-beta/.
 |
 |
 |   'Class attributes'
 |   ------------------
 |       fixtures_url(str): API-Football-Beta url to download fixtures data.
 |       league_url(str): API-Football-Beta url to find lique ID.
 |
 |   'Attributes'
 |   ------------
 |       credentials (dict): Rapid API headers - { 'x-rapidapi-key':'',  'x-rapidapi-host':''}.
 |       country_leagues_overview (pd.DataFrame): established in paralell with calling function
 |                                               'get_country_leagues_overview'
 |
 |  Methods defined here:
 |
 |  __init__(self, credentials)
 |      Initialize self.  See help(type(self)) for accurate signature.
 |
 |  get_country_leagues_overview(self, country)
 |      Find and get league ID by providing country name.
 |
 |      Parameters
 |      ----------
 |
 |      country (str): country name in english language.
 |
 |      Returns
 |      ----------
 |      pandas.core.frame.DataFrame: table with leagues description for requested country.
 |
 |  get_fixtures_data(self, league_id, seasons)
 |      Get fixtures data from Api-Football-Beta.
 |
 |      Parameters
 |      ----------
 |
 |      leauge_id (str or int): API-Football-Beta league ID for request.
 |
 |      seasons (list or int): 'list (str or int)' of league seasons. 'Int' for single season for request.
 |
 |      Returns
 |      ----------
 |      pandas.core.frame.DataFrame: concatenated pandas DataFrame object.
 |
 |  get_seasons_details(self, league_id)
 |      Get seasons details - availability, years, start and end of season.
 |      Method requires calculated 'country_leagues_overview' attribute by running method
 |      'get_country_leagues_overview'.
 |
 |      Parameters
 |      ----------
 |
 |      league_id (str): API-Football-Beta league ID.
 |
 |      Returns
 |      ----------
 |      pandas.core.frame.DataFrame: table with leagues description for requested country.
 |
 |  ----------------------------------------------------------------------
 |  Data descriptors defined here:
 |
 |  __dict__
 |      dictionary for instance variables (if defined)
 |
 |  __weakref__
 |      list of weak references to the object (if defined)
 |
 |  ----------------------------------------------------------------------
 |  Data and other attributes defined here:
 |
 |  fixtures_url = 'https://api-football-beta.p.rapidapi.com/fixtures'
 |
 |  league_url = 'https://api-football-beta.p.rapidapi.com/leagues'

#### 1. Connecting to the API and searching for league details:

In [4]:
api = GetApiFootballData(credentials)

Response status code: 200
Connection successfull.

In [5]:
spain = api.get_country_leagues_overview('Spain')

In [6]:
spain.head()

                      league.name league.type country.name
league.id
140                       La Liga      League        Spain
141              Segunda Division      League        Spain
142        Primera Division Women      League        Spain
556                     Super Cup         Cup        Spain
143                  Copa del Rey         Cup        Spain

In [7]:
# seasons details - segunda division id - 141
api.get_seasons_details(141)

country.name               Spain
league.name     Segunda Division
Name: 141, dtype: object

   year       start         end
0  2016  2016-08-19  2017-06-24
1  2017  2017-08-18  2018-06-16
2  2018  2018-08-17  2019-06-16
3  2019  2019-08-17  2020-08-23
4  2020  2020-09-12  2021-06-20
5  2021  2021-08-13  2022-05-29

#### 2. Download and save data as csv (seasons 2018, 2019, 2020):

In [8]:
fixtures_raw_data = api.get_fixtures_data(league_id=141, seasons=[2018,2019,2020])

In [9]:
fixtures_raw_data.head()

,fixture.id,fixture.referee,fixture.timezone,fixture.date,fixture.timestamp,fixture.periods.first,fixture.periods.second,fixture.venue.id,fixture.venue.name,fixture.venue.city,...,goals.home,goals.away,score.halftime.home,score.halftime.away,score.fulltime.home,score.fulltime.away,score.extratime.home,score.extratime.away,score.penalty.home,score.penalty.away
0,27519,"Valentin Pizarro Gomez, Spain",UTC,2018-08-17T20:00:00+00:00,1534536000,1534536000,1534539600,NaN,Carlos Belmonte,Albacete,...,1,1,0.0,0.0,1,1,None,None,None,None
1,27520,"Jorge Figueroa Vazquez, Spain",UTC,2018-08-18T18:30:00+00:00,1534617000,1534617000,1534620600,NaN,Santo Domingo,Alcorcon,...,1,1,0.0,0.0,1,1,None,None,None,None
2,27521,"Daniel Jesus Trujillo Suarez, Spain",UTC,2018-08-17T18:00:00+00:00,1534528800,1534528800,1534532400,1463.0,Estadio Ramon de Carranza,Cadiz,...,1,0,0.0,0.0,1,0,None,None,None,None
3,27522,"Isidro Diaz de Mera Escuderos, Spain",UTC,2018-08-18T20:00:00+00:00,1534622400,1534622400,1534626000,1469.0,Estadio Nuevo Arcángel,Cordoba,...,3,3,1.0,0.0,3,3,None,None,None,None
4,27523,"Santiago Varon Aceiton,",UTC,2018-08-18T17:00:00+00:00,1534611600,1534611600,1534615200,1473.0,Estadio Manuel Martínez Valero,Elche,...,0,0,0.0,0.0,0,0,None,None,None,None

In [10]:
fixtures_raw_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1402 entries, 0 to 1401
Data columns (total 38 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   fixture.id              1402 non-null   int64
 1   fixture.referee         1381 non-null   object
 2   fixture.timezone        1402 non-null   object
 3   fixture.date            1402 non-null   object
 4   fixture.timestamp       1402 non-null   int64
 5   fixture.periods.first   1402 non-null   int64
 6   fixture.periods.second  1402 non-null   int64
 7   fixture.venue.id        1022 non-null   float64
 8   fixture.venue.name      1402 non-null   object
 9   fixture.venue.city      1394 non-null   object
 10  fixture.status.long     1402 non-null   object
 11  fixture.status.short    1402 non-null   object
 12  fixture.status.elapsed  1402 non-null   int64
 13  league.id               1402 non-null   int64
 14  league.name             1402 non-null   object
 15  league.country          1402 non-null   object
 16  league.logo             1402 non-null   object
 17  league.flag             1402 non-null   object
 18  league.season           1402 non-null   int64
 19  league.round            1402 non-null   object
 20  teams.home.id           1402 non-null   int64
 21  teams.home.name         1402 non-null   object
 22  teams.home.logo         1402 non-null   object
 23  teams.home.winner       966 non-null    object
 24  teams.away.id           1402 non-null   int64
 25  teams.away.name         1402 non-null   object
 26  teams.away.logo         1402 non-null   object
 27  teams.away.winner       966 non-null    object
 28  goals.home              1402 non-null   int64
 29  goals.away              1402 non-null   int64
 30  score.halftime.home     1381 non-null   float64
 31  score.halftime.away     1381 non-null   float64
 32  score.fulltime.home     1402 non-null   int64
 33  score.fulltime.away     1402 non-null   int64
 34  score.extratime.home    0 non-null      object
 35  score.extratime.away    0 non-null      object
 36  score.penalty.home      0 non-null      object
 37  score.penalty.away      0 non-null      object
dtypes: float64(3), int64(13), object(22)
memory usage: 416.3+ KB

In [11]:
fixtures_raw_data['league.season'].unique()

array([2018, 2019, 2020], dtype=int64)

In [12]:
from draw_analysis.draw_analysis import DrawAnalysis

# save csv to backup folder
from draw_analysis.functions import df_to_csv_backup

In [13]:
df_to_csv_backup(fixtures_raw_data, 'segunda_division_fixtures_2018_2019_2020')

In [14]:
segunda_division = DrawAnalysis(fixtures_raw_data)

 Data description:
 ========================================
	Country: Spain
 	League name: Segunda Division
 	League id: 141
 	Seasons: 2018, 2019, 2020
 ========================================

In [15]:
fixtures_processed = segunda_division.fixtures_data
fixtures_processed.head()

,fixture_id,fixture_date,fixture_timestamp,league_id,league_name,league_country,league_season,league_round,teams_home_id,teams_home_name,...,teams_away_winner,goals_home,goals_away,score_halftime_home,score_halftime_away,halftime_goals_total,fulltime_goals_total,match_result,halftime_match_result,fulltime_match_result
0,27521,2018-08-17 18:00:00+00:00,1534528800,141,Segunda Division,Spain,2018,Regular Season - 1,724,Cadiz,...,False,1,0,0,0,0,1,1,0:0,1:0
1,27519,2018-08-17 20:00:00+00:00,1534536000,141,Segunda Division,Spain,2018,Regular Season - 1,722,Albacete,...,NaN,1,1,0,0,0,2,0,0:0,1:1
2,27523,2018-08-18 17:00:00+00:00,1534611600,141,Segunda Division,Spain,2018,Regular Season - 1,797,Elche,...,NaN,0,0,0,0,0,0,0,0:0,0:0
3,27526,2018-08-18 17:30:00+00:00,1534613400,141,Segunda Division,Spain,2018,Regular Season - 1,716,Lugo,...,True,1,2,1,0,1,3,2,1:0,1:2
4,27520,2018-08-18 18:30:00+00:00,1534617000,141,Segunda Division,Spain,2018,Regular Season - 1,711,Alcorcon,...,NaN,1,1,0,0,0,2,0,0:0,1:1

In [16]:
fixtures_processed.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1386 entries, 0 to 1385
Data columns (total 23 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   fixture_id             1386 non-null   int64
 1   fixture_date           1386 non-null   datetime64[ns, UTC]
 2   fixture_timestamp      1386 non-null   int64
 3   league_id              1386 non-null   int64
 4   league_name            1386 non-null   category
 5   league_country         1386 non-null   category
 6   league_season          1386 non-null   int64
 7   league_round           1386 non-null   category
 8   teams_home_id          1386 non-null   int64
 9   teams_home_name        1386 non-null   category
 10  teams_home_winner      953 non-null    category
 11  teams_away_id          1386 non-null   int64
 12  teams_away_name        1386 non-null   category
 13  teams_away_winner      953 non-null    category
 14  goals_home             1386 non-null   int64
 15  goals_away             1386 non-null   int64
 16  score_halftime_home    1386 non-null   int64
 17  score_halftime_away    1386 non-null   int64
 18  halftime_goals_total   1386 non-null   int64
 19  fulltime_goals_total   1386 non-null   int64
 20  match_result           1386 non-null   int64
 21  halftime_match_result  1386 non-null   category
 22  fulltime_match_result  1386 non-null   category
dtypes: category(9), datetime64[ns, UTC](1), int64(13)
memory usage: 170.3 KB

In [17]:
# saving processed fixtures data for Power BI
df_to_csv_backup(fixtures_processed, 'segunda_division_fixtures_2018_2019_2020', tail_name='processed')